 !**** DESCRIPTION: _______________________________________________________________________________________
 !                  The program is used to extract histgram of displacements generated by MD simulations 
 !
 !**** NOTE:        The defect type defined by variable DefTyp is subjected to changes
 !
 !**** USAGE:       _______________________________________________________________________________________
 !                  DisHistgram.exe -s "filename" -T(est) t1, t2, ts -C(fg) c1, c2, cs 
 !                  where:
 !                        -s filename:          - the pathname of files storing the XYZ configurations generated by
 !                                                 other anaysis programs
 !                  OPTIONS
 !                        -T(est) t1, t2, ts:   - the range for the tests to be involved in analysis
 !                        -C(est) c1, c2, cs:   - the range for the configurations to be involved
 !                  ______________________________________________________________________________________
 !**** HISTORY:
 !                  1st version   2019-04 (Hou Qing Sichuan university)
 !
 !

 
 !**********************************************************************************
 Program DisHistgram_Main
 use MD_SimBoxArray_ToolShell_14_CPU
 implicit none
    type(SimMDCtrl)    ::CtrlParam
    type(SimMDBox)     ::SimBox0, SimBox1
    type(MDRecordStamp)::Stamp0,  Stamp1
    character*256      ::InFname  = "", OutFname="", Fname="" 
    character*256      ::GFile0="", GFile1   = "" 

    integer            ::IB, IC0, IC1, IA, INB, NS, hFile
    logical            ::EX0, EX1
    real(KINDDF)       ::DIS, VEC(3), DIS00(3), DIS0(3), DIS1(3)
    real(KINDDF),parameter::BINS = 0.5D0 !0.5D0/1.4D0/2.D0
    integer,     parameter::BINN = 2000
    integer,dimension(BINN)::His
    !--- NOTE the variable DefTyp subjected to changes
    integer            ::DefTyp=2


      !*************************************
        call ExtractCmdlineFileNames_Globle_Variables()
        call CommandlineBoxsel(CtrlParam)
        InFname = gm_cfgFileName(1)
        call GetPath(InFname, OutFname)
        call GetFname(InFname, Fname)
        OutFname = OutFname(1:len_trim(OutFname)-1)//"_"//Fname(1:len_trim(Fname))//".DisHis"
        print *, OutFname

        IC0 = CtrlParam%STARTCFG
        IC1 = IC0 + CtrlParam%CFGSTEP 
        His = 0
        print *, CtrlParam%JOBID0, CtrlParam%JOBID1
        pause
        do while(.true.) 
           do IB = CtrlParam%JOBID0, CtrlParam%JOBID1
              call STRCATI(GFILE0, InFname, "P", 0, 4)
              call STRCATI(GFILE0, GFILE0, "_", IB,  4)
              call STRCATI(GFILE0, GFILE0, ".", IC0, 4)

              call STRCATI(GFILE1, InFname, "P", 0, 4)
              call STRCATI(GFILE1, GFILE1, "_", IB,  4)
              call STRCATI(GFILE1, GFILE1, ".", IC1, 4)

              inquire(FILE=GFILE0, EXIST=EX0)
              inquire(FILE=GFILE1, EXIST=EX1)

              if(.not. EX0) then
                  write(*,*)  'MDPSCU Warning: '//GFILE0(1:len_trim(GFILE0))//' not exsit'
                  exit 
               end if
               if(.not. EX1) then
                  write(*,*)  'MDPSCU Warning: '//GFILE1(1:len_trim(GFILE1))//' not exsit'
                  exit 
               end if

               write(*,*) "Load configuration from ", GFILE0(1:len_trim(GFILE0) )
               call Load_Config_SimMDBox(GFILE0, SimBox0, Stamp0)
               DIS0 = 0.D0
               NS   =  0
               do IA=1, SimBox0%NPRT
                  if(SimBox0%ITYP(IA) .ne. DefTyp) then
                     NS = NS + 1
                     DIS0(1:3) =  DIS0(1:3) + SimBox0%DIS(IA,1:3)
                  end if   
               end do   
               DIS0(1:3) = DIS0(1:3)/dble(NS)

               write(*,*) "Load configuration from ", GFILE1(1:len_trim(GFILE1) )
               call Load_Config_SimMDBox(GFILE1, SimBox1, Stamp1)
               DIS1 = 0.D0
               NS   =  0
               do IA=1, SimBox1%NPRT
                  if(SimBox1%ITYP(IA) .ne. DefTyp) then
                     NS = NS + 1
                     DIS1(1:3) =  DIS1(1:3) + SimBox1%DIS(IA,1:3)
                  end if   
               end do   
               DIS1(1:3) = DIS1(1:3)/dble(NS)
               !print *, Stamp1%Time, Stamp0%Time, Stamp1%Time-Stamp0%Time
               do IA=1, SimBox0%NPRT
                  if(SimBox0%ITYP(IA) .eq. DefTyp) then
                     VEC(1:3) = (SimBox1%DIS(IA,1:3) -SimBox0%DIS(IA,1:3)) - (DIS1(1:3) - DIS0(1:3))
                     DIS      = dsqrt(sum(VEC*VEC))/SimBox0%RR
                     INB      = int(DIS/BINS)+ 1
                     His(INB) = His(INB) + 1     
                  end if   
               end do
           end do           
           if(.not.ex0 .or. .not.ex1 ) exit
           IC0 = IC0 + 1
           IC1 = IC1 + 1
           if(IC0 .gt. CtrlParam%ENDCFG) then
              exit
           end if   
       end do     
       !***********
       call AvailableIOUnit(hFile)
       open(UNIT=hFile, FILE=OutFname)
       write(hFile, *) "! DISHis from "//InFname(1:len_trim(InFname))
       write(hFile, *) "! For CFG=", CtrlParam%STARTCFG, CtrlParam%ENDCFG, CtrlParam%CFGSTEP 
       write(hFile, *) "! Time interval=", Stamp1%Time-Stamp0%Time 
       do IB = 1, size(His)
         write(hFile, fmt="(I8,1x,1PE14.4,1x,I8,1x,1PE14.4)")  IB, (IB-1)*BINS, His(IB), dble(His(IB))/dble(NS)/CP_FOURPI/(I*BINS)**2
       end do 
       close(hFile)
       stop
 End program DisHistgram_Main

