 !**** DESCRIPTION: _______________________________________________________________________________________
 !                  The program is used to extract dispalcements of point defects from configuration
 !                  files generated by MD simulations. The outpu displacements could be used
 !                  by MSDTracking.F90 for the calculation of MSD of the defects atoms.
 !                  The extention of files of output is ".DisTracking  "
 ! 
 !                  SEE ALSO: 
 !                            MDSTracking1.F90, MDSTracking2.F90, DisSIATracking0.F90
 !
 !**** NOTE:        The defult defect type defined by variable DefTyp is subjected to changes
 !
 !**** NOTE:        The configurations are the common files created by GMD programs. 
 !                  If you want extract the displacement of the defect clusters from TRACK files generated by, 
 !                  Trajectories_GPU.F90, the program DisNeighbore0.F90 should be used.
 !             
 !**** USAGE:       _______________________________________________________________________________________
 !                  DisTracking0.F90.exe -I "filename" -T(est) t1, t2, ts -C(fg) c1, c2, cs -B(ox) b1, b2, b3
 !                  OPTIONS
 !                        -T(est) t1, t2:   - the range for the tests to be involved in analysis
 !                        -C(est) c1, c2:   - the range for the configurations to be involved
 !                  ______________________________________________________________________________________
 !**** HISTORY:
 !                  1st version   2019-04 (Hou Qing Sichuan university)
 !
 !

 
 !**********************************************************************************
 Program DisTracking0_Main
 use MD_SimBoxArray_ToolShell_14_CPU
 implicit none
    type(SimMDCtrl)    ::CtrlParam
    type(SimMDBox)     ::SimBox0, SimBox1
    type(MDRecordStamp)::Stamp0,  Stamp1
    character*256      ::InFname  = "", OutFname="", Fname="", cmdline 
    character*256      ::GFile0="", GFile1   = "" 

    integer            ::IB, IC0, IC1, IA, INB, NS, hFile, I, NP
    logical            ::EX0, EX1
    real(KINDDF)       ::DIS, VEC(3), DIS00(3), DIS0(3), XP(3), EKIN, EPOT
    real(KINDDF),parameter::BINS = 0.5D0 !0.5D0/1.4D0/2.D0
    integer,     parameter::BINN = 2000
    integer,dimension(BINN)::His
    !--- NOTE the variable DefTyp subjected to changes
    integer            ::DefTyp=2
    character*8        ::tstr(3)=""

      !*************************************
        call ExtractCmdlineFileNames_Globle_Variables()
        call get_command(cmdline)
        I = index(cmdline, gm_ExeName(1:len_trim(gm_ExeName)))
        I = I+len_trim(gm_ExeName)
        cmdline = cmdline(I:len_trim(cmdline))
        call extract_optstr(cmdline, "-","P", 1, NP, tstr)
        if(NP .ge. 1) then
           DefTyp = ISTR(tstr(1))
        end if    

        call CommandlineBoxsel(CtrlParam)
        InFname = gm_cfgFileName(1)
        call GetPath(InFname, OutFname)
        call GetFname(InFname, Fname)
        OutFname = OutFname(1:len_trim(OutFname)-1)//"_"//Fname(1:len_trim(Fname))//".DisTracking"

        call AvailableIOUnit(hFile)
        open(UNIT=hFile, FILE=OutFname)
        write(hFile, fmt="(A7, A7, A9, 10(A15))") "IB", "ICFG", "ITime", "TIME", "X", "Y", "Z", "DISX", "DISY", "DISZ", "EKIN", "EPOT"

        do IB = CtrlParam%JOBID0, CtrlParam%JOBID1
           do IC0 = CtrlParam%STARTCFG, CtrlParam%ENDCFG 
              call STRCATI(GFILE0, InFname, "P", 0, 4)
              call STRCATI(GFILE0, GFILE0, "_", IB,  4)
              call STRCATI(GFILE0, GFILE0, ".", IC0, 4)

              inquire(FILE=GFILE0, EXIST=EX0)

              if(.not. EX0) then
                  write(*,*)  'MDPSCU Warning: '//GFILE0(1:len_trim(GFILE0))//' not exsit'
                  exit 
               end if

               write(*,*) "Load configuration from ", GFILE0(1:len_trim(GFILE0) )
               call Load_Config_SimMDBox(GFILE0, SimBox0, Stamp0)
               DIS0 = 0.D0
               XP   = 0.D0
               EKIN = 0.D0
               EPOT = 0.D0
               NS   =  0
               do IA=1, SimBox0%NPRT
                  if(SimBox0%ITYP(IA) .eq. DefTyp) then
                     NS = NS + 1
                     DIS0(1:3) =  DIS0(1:3) + SimBox0%DIS(IA,1:3)/SimBox0%RR
                     XP(1:3)   =  XP(1:3)   + SimBox0%XP(IA,1:3)/SimBox0%RR
                     EKIN      =  EKIN      + SimBox0%EKIN(IA)
                     EPOT      =  EPOT      + SimBox0%EPOT(IA)
                     !print *, IA, SimBox0%XP(IA,1:3), SimBox0%DIS(IA,1:3)
                     !print *, IA, XP(1:3), DIS0(1:3)
                     !pause
                  end if   
               end do   
               DIS0(1:3) = DIS0(1:3)/dble(NS)
               XP(1:3)   = XP(1:3)/dble(NS)
               EKIN      = EKIN/dble(NS)
               EPOT      = EPOT/dble(NS)
               write(hFile, fmt="(I6,1x,I6, 1x,I8, 1x, 1PE14.6, 1x,8(1pE14.6,1x))") IB, IC0, Stamp0%ITIME, Stamp0%TIME, XP(1:3), DIS0(1:3), EKIN*CP_ERGEV, EPOT*CP_ERGEV
           end do           
        end do     
       !***********

       close(hFile)
       stop
 End program DisTracking0_Main

