 !**** DESCRIPTION: _______________________________________________________________________________________
 !                  The program is used to calculate the distances between the nearest neighbors arounds atoms of PType type
 !                  The configurations are loaded from configurations generated by MD simulations.
 !
 !                  SEE ALSO ____________________________________________________________________________
 !
 !**** USAGE:       _______________________________________________________________________________________
 !
 !                  NeastNeiborsPType.exe -s "filename" -T(est) t1, t2, ts -C(fg) c1, c2, cs -p type
 !                  where:
 !                        -s filename:          - the pathname of files storing the configuration clustering configurations generated by
 !                                                 Cfg_Track_Cluster_GPU.exe
 !                  OPTIONS
 !                        -T(est) t1, t2, ts:   - the range for the tests to be involved in analysis
 !                        -C(est) c1, c2, cs:   - the range for the configurations to be involved in analysis
 !
 !                  ______________________________________________________________________________________
 !**** HISTORY:
 !                  version 1st 2017-11 (Hou Qing, Sichuan university)
 !
 !

 module NeastNeiborsPType
   use MD_TYPEDEF_SimMDBox
   use MD_TYPEDEF_SimMDCtrl
   implicit none
        integer, private::m_PType = 0
 contains


   !**********************************************************************************
   subroutine MyPreRecord(SimBox, CtrlParam)
   !***  PURPOSE:  to initialize the calculation 
   use MD_Globle_Variables
   implicit none
  !----   DUMMY Variables
   type(SimMDBox)  ::SimBox
   type(SimMDCtrl) ::CtrlParam

  !----   Local variables
   character*256      ::cmdline
   character*8        ::tstr(3)=""
   integer            ::I, NP

       call get_command(cmdline)
       I = index(cmdline, gm_ExeName(1:len_trim(gm_ExeName)))
       I = I + len_trim(gm_ExeName)
       cmdline = cmdline(I:len_trim(cmdline))
       call extract_optstr(cmdline, "-","P", 1, NP, tstr)
       if(NP .lt. 1) then
         write(*,*) "Error: central particle type is missed"
         stop
        end if    
        m_PType = Istr(tstr(1))
     
        CtrlParam%NB_NEAREST = 64
        return
   end subroutine MyPreRecord
  !**********************************************************************************
  !**********************************************************************************
  subroutine MyRecord(Stamp, SimBox, CtrlParam)
  !***  DESCRIPTION: to calcualte and putout the occupation state of lattice and interstials
  !                  identified using method#1
  !
  !    INPUT:  Stamp,       the recoding stamp
  !            SimBox,      the simulation boxs
  !            CtrlParam,   the control parameters for simulation
  !
   use MD_NeighborsList
   use MD_NeighborsList_GPU
   implicit none
       !--- dummy variables
       type(MDRecordStamp) ,           intent(in)::Stamp
       type(SimMDBox), dimension(:),   intent(in)::SimBox
       type(SimMDCtrl),                intent(in)::CtrlParam
       !--- local variables
       integer::IB, I, K, IP, STARTP, IW, NN, IND, hFile
       !----
       character*256::InFname, OutFname, GFILE
       real(KINDDF)::VECT1(3), HBS(3), BS(3), DIST, LATT
       type(NEIGHBOR_LIST)::List

        call Copyout_NeighboreList_DEV(List, ORDER=1)
        InFname = gm_cfgFileName(1)
        call GetFname(InFname, OutFname)
        call STRCATI(GFILE, OutFname, "P", 0, 4)
        call STRCATI(GFILE, GFILE, "_", Stamp%ITEST, 4)
        call STRCATI(GFILE, GFILE, ".", Stamp%ICFG(1), 4)

        call AvailableIOUnit(hFile)
        open(UNIT=hFile, FILE=GFILE)

          IP     = 0
          STARTP = 0
          do IB=1, size(SimBox)
             BS  = SimBox(IB)%ZL
             HBS = 0.5D0*BS
             LATT = SimBox(IB)%RR
             do I=1, SimBox(IB)%NPRT 
                IP = IP + 1 
                if(SimBox(IB)%ITYP(I) .ne. m_PType) cycle
                NN = List%KVOIS(IP)
                do IW = 1, NN   
                   IND = List%INDI(IP,IW) - STARTP
                   do K=1,3
                      VECT1(K) = SimBox(IB)%XP(I,K) -SimBox(IB)%XP(IND,K)
                      if(dabs(VECT1(K)) .GT. HBS(K)) then
                         VECT1(K) = VECT1(K) - DSIGN(BS(K),VECT1(K))
                      end if
                   end do
                   DIST = dsqrt(sum(VECT1*VECT1))
                   write(hFile,fmt="I5, 1x, 2(I6,1x), 4(1PE14.6,1x)" ) Stamp%ITest, IB, I, VECT1/LATT, DIST/LATT
                end do
             end do
             STARTP = IP
          end do   
          close(hFile)
 end subroutine MyRecord
 !****************************************************************************

 !**********************************************************************************
   subroutine MyAftRecord(SimBox, CtrlParam)
   !***  PURPOSE:  to initialize the calculation 
   implicit none
  !----   DUMMY Variables
   type(SimMDBox)  ::SimBox
   type(SimMDCtrl) ::CtrlParam

  !----   Local variables
         return
   end subroutine MyAftRecord
  !**********************************************************************************

 end module NeastNeiborsPType

 !**********************************************************************************
 Program NeastNeiborsPType_Main
 use MD_SimBoxArray_ToolShell_14_GPU
 use NeastNeiborsPType
 implicit none


       call APPSHELL_AddRecord(AFTRECORD=MyAftRecord, PRERECORD=MyPreRecord, RECORDPROC=MyRecord)
       call Multi_ANALYSIS(0)

       stop
 End program NeastNeiborsPType_Main
