 !**** DESCRIPTION: _______________________________________________________________________________________
 !                  The program is to do statistical calcultion on the time intervals betwwen events
 !                  generated by EventSearch_GPU 
 !
 !                  SEE ALSO ____________________________________________________________________________
 !                       EventSearch_GPU.F90
 !
 !
 !**** USAGE:       _______________________________________________________________________________________
 !
 !                  EventSearch_times.F90.exe -s "filename" -T(est) t1, t2, ts -C(fg) c1, c2, cs
 !                  where:
 !                        -s filename:          -  the pathname of files storing the configuration clustering configurations generated by
 !                                                 Cfg_Track_Cluster_GPU.exe
 !                  OPTIONS
 !                        -T(est) t1, t2, ts:   - the range for the tests to be involved in analysis
 !                        -C(est) c1, c2, cs:   - the range for the configurations to be involved in analysis
 !
 !                  ______________________________________________________________________________________
 !**** HISTORY:
 !                  version 1st 2019-03 (Hou Qing, Sichuan university)
 !
 !

 module RandPower_Test_M
 use RAND32_MODULE
 use MSM_CONSTANTS
 implicit none
 contains

   !**********************************************************************************
   subroutine RandPow(X0, P, X )
   !***  PURPOSE:  to generate a random number followinfg ditribution:
   !               f(x) = P*X0**P/(X0+X)**(1+P), with P>0    
   implicit none
  !----   DUMMY Variables
   real(KINDDF), intent(in) ::X0, P 
   real(KINDDF), intent(out)::X 

  !----   Local variables
       real(KINDDF)::R
                       
            R = DRAND32()
            !call Random_Number(R)
            X = X0*(R**(-1.D0/P)-1.D0)
   end subroutine RandPow
  !**********************************************************************************

   !**********************************************************************************
   subroutine RandExp(X0, X )
   !***  PURPOSE:  to generate a random number followinfg ditribution:
   !               f(x) = exp(-X/X0)/X0
   implicit none
  !----   DUMMY Variables
   real(KINDDF), intent(in) ::X0
   real(KINDDF), intent(out)::X 

  !----   Local variables
       real(KINDDF)::R
                       
            R = DRAND32()
            X = -X0*dlog(R)
   end subroutine RandExp
 !**********************************************************************************   

 !**********************************************************************************
 subroutine RandPower_Test0(X0, P)
 implicit none
 real*8 ::X0, P
 real*8 ::X, BW
 integer, parameter::RES = 20
 integer, parameter::NBIN = 500*RES
 real*8 ::tHIS(NBIN)=0
 integer::NE = NBIN*1000
 integer::I, IB

       tHIS = 0
       BW = X0/dble(RES) 
       do I =1, NE 
          call RandPow(X0, P, X)
          
          IB = int(X/BW) + 1
          IB = min(IB, NBIN)
          if(IB .le. 0 .or. IB.gt.NBIN) then
             print *, "IB", I, X, IB
             pause
          end if      
          !print *,X, IB
          if(IB .gt. 0) tHIS(IB) = tHIS(IB) + 1
       end do      

       open(unit=10, file="Randpow_test0.out")
       do IB=1, NBIN
          write(10, fmt="(4(1PE16.4,1x))") IB*BW, tHIS(IB)
       end do 
       close(10)  
       
       return
  end subroutine RandPower_Test0
  !**********************************************************************************

 !**********************************************************************************
 subroutine RandExp_Test0(X0)
 implicit none
 real*8 ::X0, P
 real*8 ::X, BW
 integer, parameter::RES = 20
 integer, parameter::NBIN = 500*RES
 real*8 ::tHIS(NBIN)=0
 integer::NE = NBIN*1000
 integer::I, IB

       tHIS = 0
       BW = X0/dble(RES) 
       do I =1, NE 
          call RandExp(X0, X)
          
          IB = int(X/BW) + 1
          IB = min(IB, NBIN)
          if(IB .le. 0 .or. IB.gt.NBIN) then
             print *, "IB", I, X, IB
             pause
          end if      
          !print *,X, IB
          if(IB .gt. 0) tHIS(IB) = tHIS(IB) + 1
       end do      

       open(unit=10, file="RandExp_test0.out")
       do IB=1, NBIN
          write(10, fmt="(4(1PE16.4,1x))") IB*BW, tHIS(IB)
       end do 
       close(10)  
       
       return
  end subroutine RandExp_Test0
  !**********************************************************************************  

 !**********************************************************************************
 subroutine Time_vs_Steps(NTEST, MNS, X0, P)
 implicit none
 integer::NTEST, MNS 
 real*8 ::X0, P
 !--- local
 real*8 ::X, BW, TX1, TXAV, TXSTD
 real*8, dimension(:), allocatable::TX
 integer::I, J


       allocate(TX(NTEST))
       !call RandPower_Test0(X0, P)
       !call RandExp_Test0(X0)

       open(unit=10, file="Randpow_test_T.out")
       write(10, fmt="(A, I, 4(1PE16.4,1x))") "!NTEST ", NTEST
       write(10, fmt="(A, I, 4(1PE16.4,1x))") "!MNS   ", MNS
       write(10, fmt="(A, 4(1PE16.4,1x))") "!X0   ", X0
       write(10, fmt="(A, 4(1PE16.4,1x))") "!P   ", P

       TX = 0.D0
       do I=1, MNS
          do J=1, NTEST
             call RandPow(X0, P, TX1)
             TX(J) = TX(J) + TX1
          end do
          TXAV  = sum(TX)/dble(NTEST)
          TXSTD = sum((TX-TXAV)**2)/dble(NTEST)
          TXSTD = dsqrt(TXSTD) 
          write(*, fmt="(I, 4(1PE16.4,1x))") I, I*X0, TXAV/X0,  TXSTD/X0, TXSTD/TXAV
          write(10, fmt="(I, 4(1PE16.4,1x))") I, I*X0, TXAV/X0, TXSTD/X0, TXSTD/TXAV
       end do   
       close(10)

       open(unit=10, file="Randexp_test_T.out")
       write(10, fmt="(A, I, 4(1PE16.4,1x))") "!NTEST ", NTEST
       write(10, fmt="(A, I, 4(1PE16.4,1x))") "!MNS   ", MNS
       write(10, fmt="(A, 4(1PE16.4,1x))") "!X0   ", X0
       write(10, fmt="(A, 4(1PE16.4,1x))") "!P   ", P
       TX = 0.D0
       do I=1, MNS
          do J=1, NTEST
             call RandExp(X0, TX1)
             TX(J) = TX(J) + TX1
          end do
          TXAV  = sum(TX)/dble(NTEST)
          TXSTD = sum((TX-TXAV)**2)/dble(NTEST)
          TXSTD = dsqrt(TXSTD) 
          write(*, fmt="(I, 4(1PE16.4,1x))") I, I*X0, TXAV/X0, TXSTD/X0, TXSTD/TXAV
          write(10, fmt="(I, 4(1PE16.4,1x))") I, I*X0, TXAV/X0, TXSTD/X0, TXSTD/TXAV
       end do   
       close(10)
       deallocate(TX) 
       return
 End subroutine Time_vs_Steps  

 !**********************************************************************************
 subroutine Dis_vs_Times(NBOX, MNS, DT, X0, P)
 !---  MNS: the number of  steps
 implicit none
 integer::NBOX, MNS 
 real*8 ::DT, X0, P
 !--- local
 real*8 ::X, BW, TX1, TR2AV, TXSTD, PITP, PITE, TT, DX
 real*8, dimension(:), allocatable::R
 integer::I, J
 character*256::FNAME0


       allocate(R(NBOX))

       PITP = 1.D0 - (X0/(X0+DT))**P
       PITE = 1.D0 - dexp(-DT/X0)
       print *, "PITP, PITE", PITP, PITE
       pause
       open(unit=10, file="Randpow_test_R.out")
       write(10, fmt="(A, I, 4(1PE16.4,1x))") "!NTEST ", NBOX
       write(10, fmt="(A, I, 4(1PE16.4,1x))") "!MNS   ", MNS
       write(10, fmt="(A, 4(1PE16.4,1x))") "!X0   ", X0
       write(10, fmt="(A, 4(1PE16.4,1x))") "!P   ", P
       R  = 0.D0
       TT = 0
       do I=1, MNS
          do J=1, NBOX
             TX1 = DRAND32() 
             if(TX1 .le. PITP) then
                if(DRAND32() .ge. 0.5D0) then
                   R(J) = R(J) + 1
                else
                   R(J) = R(J) - 1 
                end if  
             end if   
          end do
          TR2AV  = sum(R*R)/dble(NBOX)
          TT     = TT + DT
          write(*, fmt="(I, 4(1PE16.4,1x))") I, I*DT,  TT/X0,  TR2AV
          write(10, fmt="(I, 4(1PE16.4,1x))") I, I*DT, TT/X0,  TR2AV
       end do   
       close(10)
       
       open(unit=10, file="Randexp_test_R.out")
       write(10, fmt="(A, I, 4(1PE16.4,1x))") "!NTEST ", NBOX
       write(10, fmt="(A, I, 4(1PE16.4,1x))") "!MNS   ", MNS
       write(10, fmt="(A, 4(1PE16.4,1x))") "!X0   ", X0
       write(10, fmt="(A, 4(1PE16.4,1x))") "!P   ", P
       R  = 0.D0
       TT = 0
       do I=1, MNS
          do J=1, NBOX
             TX1 = DRAND32() 
             if(TX1 .le. PITE) then
               if(DRAND32() .ge. 0.5D0) then
                  R(J) = R(J) + 1
               else
                  R(J) = R(J) -1 
               end if  
            end if   
          end do
          TR2AV  = sum(R*R)/dble(NBOX)
          TT     = TT + DT
          write(*, fmt="(I, 4(1PE16.4,1x))") I, I*DT,  TT/X0,  TR2AV
          write(10, fmt="(I, 4(1PE16.4,1x))") I, I*DT, TT/X0,  TR2AV
       end do   
       close(10)
       deallocate(R) 
       return
 End subroutine Dis_vs_Times  


 end module RandPower_Test_M

 !**********************************************************************************
 Program RandPower_Test_Main
 use RandPower_Test_M
 implicit none
 integer, parameter::NTEST = 1000000, MNS=100, NS=100 
 real*8 ::TX(NTEST)=0
 real*8 ::X0, P, X, BW, TX1, TXAV, TXSTD
 integer::I, J
 integer::ISEED0, ISEED(2)=(/3555, 5443/)


       call DRAND32_PUTSEED(ISEED) 
       X0 = 1
       P  = 5
       !call RandPower_Test0(X0, P)
       !call RandExp_Test0(X0)
       call Time_vs_Steps(NTEST, MNS, X0, P)
       call Dis_vs_Times(NTEST, MNS, X0/dble(NS), X0, P)
       stop
 End program RandPower_Test_Main
