 !**** DESCRIPTION: _______________________________________________________________________________________
 !                  The program is used to calculte the local structre of SIA dimer. With
 !                  the configuration created by Cfg_Track_Cluster_GPU
 !
 !                  SEE ALSO ____________________________________________________________________________
 !                       Cfg_Track_Cluster_GPU.F90
 !
 !
 !**** USAGE:       _______________________________________________________________________________________
 !
 !                  SAI_Dimer_Strcut.exe -s "filename" -T(est) t1, t2, ts -C(fg) c1, c2, cs
 !                  where:
 !                        -s filename:          - the pathname of files storing the configuration clustering configurations generated by
 !                                                 Cfg_Track_Cluster_GPU.exe
 !                  OPTIONS
 !                        -T(est) t1, t2, ts:   - the range for the tests to be involved in analysis
 !                        -C(est) c1, c2, cs:   - the range for the configurations to be involved in analysis
 !
 !                  ______________________________________________________________________________________
 !**** HISTORY:
 !                  version 1st 2017-11 (Hou Qing, Sichuan university)
 !
 !

 module SIA_Dimer_Struct
 use MD_TYPEDEF_SimMDBox
 use MD_TYPEDEF_SimMDCtrl
 implicit none
      integer, private::m_hFile = 0
 contains

   !**********************************************************************************
   subroutine MyPreRecord(SimBox, CtrlParam)
   !***  PURPOSE:  to initialize the calculation 
   use MD_Globle_Variables
   implicit none
  !----   DUMMY Variables
   type(SimMDBox) ::SimBox
   type(SimMDCtrl)::CtrlParam

  !----   Local variables
          
            call AvailableIOUnit(m_hFile)
            call ExtractExeName_Globle_Variables()
            open(UNIT=m_hFile, FILE=gm_ExeName(1:len_trim(gm_ExeName))//".out")
         return
   end subroutine MyPreRecord
  !**********************************************************************************
  !**********************************************************************************
  subroutine MyRecord(Stamp, SimBox, CtrlParam)
  !***  DESCRIPTION: to calcualte and putout the occupation state of lattice and interstials
  !                  identified using method#1
  !
  !    INPUT:  Stamp,       the recoding stamp
  !            SimBox,      the simulation boxs
  !            CtrlParam,   the control parameters for simulation
  !
  implicit none
       !--- dummy variables
       type(MDRecordStamp) ,         intent(in):: Stamp
       type(SimMDBox), dimension(:), intent(in)::SimBox
       type(SimMDCtrl),              intent(in)::CtrlParam
       !--- local variables
       integer::I
       real(KINDDF), dimension(:), allocatable::DE
       real(KINDDF)::MXE, MIE
       !----
       real(KINDDF)::VECT1(3), VECT2(3), VECT3(3), SWAP
       integer::FLAG

          VECT1(1:3) = SimBox(1)%XP(2,1:3) - SimBox(1)%XP(1,1:3)
          VECT2(1:3) = SimBox(1)%XP(3,1:3) - SimBox(1)%XP(1,1:3)
          VECT3(1:3) = SimBox(1)%XP(3,1:3) - SimBox(1)%XP(2,1:3)
          do while(.true.)
             FLAG = 0
             do I=1, size(VECT3)-1
                if(dabs(VECT3(I)).gt.dabs(VECT3(I+1))) then
                   SWAP = VECT3(I+1)  
                   VECT3(I+1) = VECT3(I)
                   VECT3(I) = SWAP
                   FLAG = 1 
                end if 
             end do
             if(FLAG .eq. 0) exit
          end do
          write(m_hFile, fmt="(10(1PE14.6,1X))") &
                                          sum(VECT1*VECT2)/dsqrt(sum(VECT1*VECT1))/dsqrt(sum(VECT2*VECT2)), &
                                          dabs(VECT3)/SimBox(1)%RR,                                               &   
                                          dsqrt(sum(VECT3*VECT3))/SimBox(1)%RR                                             
 end subroutine MyRecord
 !****************************************************************************

 !**********************************************************************************
   subroutine MyAftRecord(SimBox, CtrlParam)
   !***  PURPOSE:  to initialize the calculation 
   implicit none
  !----   DUMMY Variables
   type(SimMDBox)  ::SimBox
   type(SimMDCtrl) ::CtrlParam

  !----   Local variables
          close(m_hFile)
         return
   end subroutine MyAftRecord
  !**********************************************************************************

 end module SIA_Dimer_Struct

 !**********************************************************************************
 Program SIA_Struct_Main
 use MD_SimBoxArray_ToolShell_14_CPU
 use SIA_Dimer_Struct
 implicit none


       call APPSHELL_AddRecord(AFTRECORD=MyAftRecord, PRERECORD=MyPreRecord, RECORDPROC=MyRecord)
       call Multi_ANALYSIS(0)

       stop
 End program SIA_Struct_Main
