 !**** DESCRIPTION: _______________________________________________________________________________________
 !                  The program is used to merge the configurations at different time steps, for example,
 !                  created by Cfg_Track_SIA_GPU_Main.
 !
 !                  This program could be used to visualize the change of configurations with time.
 !
 !                  SEE ALSO ____________________________________________________________________________
 !                       Cfg_Track_SIA_GPU_Main.F90
 !
 !
 !**** USAGE:       _______________________________________________________________________________________
 !                  Cfg_Track_Merge.exe -s "filename" -T(est) t1, t2, ts -C(fg) c1, c2, cs
 !                  where:
 !                        -s filename:          - the pathname of files storing the clustering configurations generated by
 !                                                 Cfg_Track_SIA_GPU.exe
 !                  OPTIONS
 !                        -T(est) t1, t2, ts:   - the range for the tests to be involved in analysis
 !                        -C(est) c1, c2, cs:   - the range for the configurations to be involved in analysis
 !                  ______________________________________________________________________________________
 !**** HISTORY:
 !                  1st version   2015-04 (Hou Qing Sichuan university)
 !
 !

 module Cfg_Track_Merge
 use MD_CONSTANTS
 use MD_TYPEDEF_SimMDBox
 use MD_TYPEDEF_SimMDCtrl
 use MD_Globle_Variables

 implicit none
       character*256  ::m_InPath  = ""
       type(SimMDCtrl)::m_CtrlParam

  contains
  !**********************************************************************************
   subroutine Initialize()
   !***  PURPOSE:  to initialize the calculation by allocate memories, and create the
   !               neighbor-list of the reference lattice
   !
   implicit none
  !----   DUMMY Variables
  !----   Local variables

  !----   Local variables
         call ExtractCmdlineFileNames_Globle_Variables()
         call CommandlineBoxsel(m_CtrlParam)
         call GetPath(gm_cfgFileName(1), m_InPath)
         return
   end subroutine Initialize
  !**********************************************************************************

  !**********************************************************************************
   subroutine MergeCfg()
  !***  DESCRIPTION: to analysis the bond information of clusters. The bond information
  !                  is descirbed in DefectBondInfo_BCC
  !
  !    INPUT:  IB,   the box IDclusters
  !
  !    OUTPUT: BONDS,    the array describing the bonds of the clusters
  !
   implicit none
       !--- dummy variables
        !--- local variables for IO
         integer::ITEST, ICFG, hFile1, hFile2
         character*256::GFILE
         type(SimMDBox)::BOX0, TRACKBOX
         type(MDRecordStamp)::STAMP
         real*8::CENTER1(3), CENTER2(3), BS(3), HBS(3), DIS(3)
  !-------------
        !--- start analysis

             do ITEST   = m_CtrlParam%JOBID0, m_CtrlParam%JOBID1, m_CtrlParam%JOBIDSTEP

                call Release_SimMDBox(TRACKBOX)
                do ICFG = m_CtrlParam%STARTCFG+m_CtrlParam%CFGSTEP,  m_CtrlParam%ENDCFG, m_CtrlParam%CFGSTEP
                   call STRCATI(GFILE, m_InPath(1:len_trim(m_InPath)), "P", 0, 4)
                   call STRCATI(GFILE, GFILE, "_", ITEST, 4)
                   call STRCATI(GFILE, GFILE, ".", ICFG, 4)
                   write(*,*) "Load configure from ", GFILE(1:len_trim(GFILE))
                   call Load_Config_SimMDBox(GFILE, BOX0)
                   call Merge_SimMDBox(BOX0, TRACKBOX)
                end do

                call STRCATI(GFILE, m_InPath(1:len_trim(m_InPath))//"merged_", "P", 0, 4)
                call STRCATI(GFILE, GFILE, "_", ITEST, 4)
                STAMP%ITest = ITEST
                STAMP%ITime = 0
                STAMP%ISect = 1
                STAMP%Time  = 0
                STAMP%ICfg  = 0
                STAMP%IRec  = 0
                write(*,fmt="(A, I6, A)") " Merged track configuration saved to  "//GFILE(1:len_trim(GFILE))//".0000"
                call Putout_Instance_Config_SimMDBox(GFILE, TRACKBOX, STAMP)
             end do

             return
   end subroutine MergeCfg
  !**********************************************************************************

 end module Cfg_Track_Merge


 !**********************************************************************************
 Program Cfg_Merge_Main
 use Cfg_Track_Merge
 implicit none

       call Initialize()
       call MergeCfg()

       stop
 End program Cfg_Merge_Main
