
!**** DESCRIPTION: _______________________________________________________________________________________
!                  The program uses EMBEDMENT_DIFFUSION_14 module to calculate the diffusion coefficiency
!                  of an atom or a cluster that embedment in a substrate.
!                  The configuration generated by MD simulations are sequentially loaded in. The displacement
!                  mass center of the embeded clusters are calculated and accumulated for all boxes (see the
!                  control parameter TOTALBOX in MD simulation) at different times. The relationship
!                  between the average displacement tensor and time are output for extraction of diffustion
!                  coefficient.
!
!
!                  DEPENDENCE____________________________________________________________________________
!                       MD_SimBoxArray_ToolShell_14_GPU.F90
!                       EMBEDMENT_DIFFUSION_14.F90
!                       EMBEDMENT library
!
!
!**** USAGE:       _______________________________________________________________________________________
!                  To use use the analysis tool, the input control files need to be prepaired.
!                  First, in the SETUP file used by the MD simulation (refer to the description of
!                  the SETUP file for MD simulations), at least one lines need to be add:
!
!                    &AUXF_EMBED  filename
!
!                  If the MD simulations were conducted by EMBEDMENT_2014.exe, the line
!                  &AUXF_EMBED filename should be already in the SETUP file.
!                  The filename should be in quotated.
!
!                  Second, the file with the name of filename, which provids the type of
!                  the embeded atoms, needs to be prepair. If the MD simulations were conducted
!                  by EMBEDMENT_2014.exe, this file should be ready. For details of prepairing
!                  this file, one may refer to the guide of running EMBEDMENT_2014.exe.
!
!                  With the input file(s) are ready, the program is run on the command line:
!
!                   EMBEDMENT_Diffusion_14.exe SETUP-file
!                   where:
!                         SETUP-file  - the name of setup file used by MD simulations in MDPSCU.
!                                       MD simulations in MDPSCU.
!
!
!**** HISTORY:     ______________________________________________________________________________________
!                  version 1st 2014-05 (Hou Qing, Sichuan university)
!

 Program EMBEDMENT_DIFFUSION_2014_Main
 use EMBEDMENT_DIFFUSION1
 use MD_SimBoxArray_ToolShell_14_CPU
 implicit none


     !****
         call APPSHELL_AddRecord(PRERECORD=Initialize, RECORDPROC=Record_Diffusion_Param, AFTRECORD=AfterRecord_Diffusion_Param)
         call Main_ANALYSIS(0)

      stop
 end  program EMBEDMENT_DIFFUSION_2014_Main
