 !**** DESCRIPTION: _______________________________________________________________________________________
 !                  The program uses RefVoronoiVacancy_2014_GPU module to identify vacancy and interstitials.
 !
 !**** ALGORITHM:
 !                  A configuration is taken as a reference configuration (RC). Each "atom" in the reference
 !                  configuration is a seed of Voronoi tessellation. Then the configurations generated by
 !                  MD simulations are sequentially loaded in. The atoms in the MD configurations are checked
 !                  to find out which Voronoi volume they are in, according to the definition of Voronoi
 !                  tessellation.
 !                  A Voronoi volume is identfied as a vacancy if no atom exist in the volume.
 !                  A Voronoi volume is identfied as an interstitial if more than two atoms exist in the volume.
 !
 !                  The search of the Voronoi volumes that the atoms are in is perfromed on GPUs. Thus, cuda
 !                  support is required for the computer.
 !
 !                  NOTE____________________________________________________________________________
 !                   the configurations must be for ONE box at different time points. If the configurations
 !                   are generated by MDPSCU with control parameter MULTIBOX larger than 1, the  results
 !                   will be wrong.
 !
 !
 !                  DEPENDENCE____________________________________________________________________________
 !                       MD_SimBoxArray_ToolShell_14_GPU.F90
 !                       RefVoronoiVA_GPU.F90
 !
 !
 !**** USAGE:       _______________________________________________________________________________________
 !                  To use the analysis tool, the input control files need to be prepaired.
 !                  First, in the SETUP file used by the MD simulation (refer to the description of
 !                  the SETUP file for MD simulations), at least one line needs to be add:
 !
 !                    &AUXF_RVVIN  filename1
 !
 !                  where filename1 is the file that provide some control parameters. Optionally,
 !                  one can also add:
 !
 !                    &AUXF_RVVOUT filename2
 !
 !                  in the setup file. The filename2 is the file name for outputing results.
 !                  It should be noted that the filenames should be in quotated.
 !
 !                  The second file needs to be prepaired is the control file denoted by filename1.
 !                  A few kewords may appear in the control file:
 !
 !                  &REFCFG        indication of the filename of the reference configurqation.
 !                                  if the reference configuration is not assigned explicitly,
 !                                  the configuration at zero time step will be the reference
 !                                  configuration.
 !
 !                                  usage:   &REFCFG filename
 !
 !                                  example: &REFCFG "Myreference.crystal"
 !
 !                   &METHOD        indication of the method used to identify the occupation
 !                                  of the reference sites.
 !
 !                                  usage:   &METHOD = name rad
 !                                           where name is a string "USEVT" (default) or "USEST".
 !                                           If name = "USEVT", a site is indentified as occupied if there is
 !                                              one or more atoms is closer to the site than to other sites.
 !                                              the site is actually a Voronoi site.
 !                                           If name = "USEST", a site is identified as occupied if ther is
 !                                              an atom is in a sphere region of given raidu cenered by the
 !                                              site. rad is the raidu of the sphere region.
 !                                  example1: &METHOD "USEVT"
 !                                  example2: &METHOD "USEST"  rad
 !
 !                   &CALFOR        indication if local force to be also calculated and output
 !                                  = 0 for no (default), = 1 for yes
 !                                  This parameter take  effects only when METHOS is "USEVT"
 !
 !                   &CALPOT        indication if local potential to be also calculated and output
 !                                  = 0 for no (default), = 1 for yes
 !                                  This parameter take  effects only when METHOS is "USEVT"
 !
 !                   &CALKEN        indication if local kinetic energy to be also calculated and output
 !                                  = 0 for no (default), = 1 for yes
 !
 !                                  This parameter take  effects only when METHOS is "USEVT"
 !                   $CALSTRESS     indication if local stress to be also calculate and output
 !
 !                   &AUXF_RVVOUT   indicating of filename of for outputing results. If the filename is
 !                                  given here, the filename2 (if given in SETUP file) will be replaced.
 !
 !                  If the filename of the reference configuration is given in the control file described
 !                  above, the third file storing the reference configuration needs to be prepaired. The
 !                  the file could be in the format of "&CFGXYZ", "&BOXCFG14" or "t-x-y-z" file whithout
 !                  header.
 !
 !                  With the input file(s) are ready, the program can be run on command line:
 !
 !                  RefVoronoiVATool_GPU.exe SETUP-file dev0  ndev
 !                  where:
 !                        SETUP-file  - the name of setup file used by MD simulations in MDPSCU.
 !                        dev0        - the ID of the first GPU to be used
 !                        ndev        - the number of GPUs to be used
 !
 !                  ______________________________________________________________________________________
 !**** HISTORY:
 !                  version 1st 2014-05 (Hou Qing, Sichuan university)
 !
 !
 Program REFVORONOIVA_TOOL_MAIN
 use MD_SimBoxArray_ToolShell_14_GPU
 use RefVoronoiVacancy_GPU

 implicit none

       call APPSHELL_AddRecord( PRERECORD=Initialize_ReferenceVacancy_DEV,  &
                                RECORDPROC=Record_ReferenceVacancy_TOOL,   &
                                AFTRECORD=Clear_WorkingArray_DEV)

       call Main_ANALYSIS(0)

       stop
 End program REFVORONOIVA_TOOL_MAIN
