 !**** DESCRIPTION: _______________________________________________________________________________________
 !                  The program is used to merge the configurations in XYZ format at different time steps,
 !                  for example, created by CentroSymParam_for_BCC_GPU.
 !
 !                  This program differ from MultBox2MergeBoxes. The present program reserve the format
 !                  of input files.
 !
 !                  This program could be used to visualize the change of configurations with time and statistical
 !                  calculations.
 !
 !
 !
 !**** USAGE:       _______________________________________________________________________________________
 !                  XYZData_Merge.exe -s "filename" -T(est) t1, t2, ts -C(fg) c1, c2, cs
 !                  where:
 !                        -s filename:          - the pathname of files storing the XYZ configurations generated by
 !                                                 other anaysis programs
 !                  OPTIONS
 !                        -T(est) t1, t2, ts:   - the range for the tests to be involved in analysis
 !                        -C(est) c1, c2, cs:   - the range for the configurations to be involved
 !
 !                  NOTE: the out file will be place in the same path of the input configurations
 !                        headed by Merged_
 !                  ______________________________________________________________________________________
 !**** HISTORY:
 !                  1st version   2015-04 (Hou Qing Sichuan university)
 !
 !

 module XYZData_Merge
 use MD_CONSTANTS
 use MD_Globle_Variables

 implicit none
       character*256::m_InFname  = ""
       type(SimMDCtrl)::m_CtrlParam

  contains
  !**********************************************************************************
   subroutine Initialize()
   !***  PURPOSE:  to initialize the calculation by allocate memories, and create the
   !               neighbor-list of the reference lattice
   !
   implicit none
  !----   DUMMY Variables
  !----   Local variables

  !----   Local variables
         call ExtractCmdlineFileNames_Globle_Variables()
         call CommandlineBoxsel(m_CtrlParam)
         m_InFname = gm_cfgFileName(1)

         return
   end subroutine Initialize
  !**********************************************************************************

  !**********************************************************************************
   subroutine MergeCfg_ICfgSerial()
  !***  DESCRIPTION: to merge a set of files of different ITEST but the same ICFG
   implicit none
   !--- dummy variables
   !--- local variables for IO
         integer::ITEST, ICFG, hFile1, hFile2, hFileH, LINE, LINEH, LINEA, NA1, NA2, FLAG, N, I, NA(mp_MXGROUP), NGROUP, LINENG, LINENA
         character*256::GFILE
         real*8::CENTER1(3), CENTER2(3), BS(3), HBS(3), DIS(3)
         character*1024::TSTR1, TSTR2
         character*64::KEYWORD, STRNUMB(10)
         logical::EX
  !-------------

             do ICFG = m_CtrlParam%STARTCFG,  m_CtrlParam%ENDCFG, m_CtrlParam%CFGSTEP
                call AvailableIOUnit(hFile2)
                open(hFile2, status='SCRATCH')
                call AvailableIOUnit(hFileH)
                open(hFileH, status='SCRATCH')

                !--- load the data
                NGROUP = 0
                NA     = 0
                NA2    =  0
                FLAG   = 0
                LINE   = 0
                LINEH  = 0
                LINEA  = 0
                LINENG = 0
                LINENA = 0
                do ITEST = m_CtrlParam%JOBID0, m_CtrlParam%JOBID1, m_CtrlParam%JOBIDSTEP

                   GFILE = m_InFname(1:len_trim(m_InFname))
                   call STRCATI(GFILE, GFILE, "P", 0, 4)
                   call STRCATI(GFILE, GFILE, "_", ITEST, 4)
                   call STRCATI(GFILE, GFILE, ".", ICFG, 4)
                   inquire(FILE=GFILE, EXIST=EX)
                   if(.not.EX) then
                      GFILE = m_InFname(1:len_trim(m_InFname))
                      call STRCATI(GFILE, GFILE, "P", 0, 4)
                      call STRCATI(GFILE, GFILE, "_", ITEST, 4)
                   end if
                   write(*,*) "Load configure from ", GFILE(1:len_trim(GFILE))
                   call AvailableIOUnit(hFile1)
                   open(hFile1, file= GFILE, status='old')
                   do while(.true.)
                      read(hFile1, fmt="(A)", end=100 )TSTR1
                      TSTR2 = TSTR1
                      TSTR1 = adjustl(TSTR1)
                      if((TSTR1(1:1) .eq. '!') .or. (TSTR1(1:1) .eq. '&') .or. len_trim(TSTR1) .le. 0) then
                         if(FLAG .eq. 0) then
                            LINEH = LINEH + 1
                            write(hFileH,fmt="(A)" )TSTR2(1:len_trim(TSTR2))
                         end if

                         if(TSTR1(1:1) .eq. '&') then
                             call GetKeyword("&", TSTR1, KEYWORD)
                             if (KEYWORD(1:len_trim(KEYWORD)) .eq. "&NATOM") then
                                 call Extract_Numb(TSTR1,1,N,STRNUMB)
                                 NA1 = ISTR(STRNUMB(1))
                                 NA2 = NA2 + NA1
                                 if(FLAG .eq. 0) LINE = LINEH
                              else if((KEYWORD(1:len_trim(KEYWORD)) .eq. "&NGROUP")) then   
                                 call Extract_Numb(TSTR1,1,N,STRNUMB)
                                 NGROUP = max(NGROUP, ISTR(STRNUMB(1)) )
                                 if(FLAG .eq. 0) LINENG = LINEH
                              else if((KEYWORD(1:len_trim(KEYWORD)) .eq. "&NA")) then   
                                 call Extract_Numb(TSTR1,mp_MXGROUP,N,STRNUMB)
                                 do I=1, N
                                    NA(I) = NA(I) + ISTR(STRNUMB(I))
                                 end do  
                                 if(FLAG .eq. 0) LINENA = LINEH 
                              end if
                         end if
                      else
                         FLAG = 1
                         LINEA = LINEA  + 1
                         write(hFile2,fmt="(A)" )TSTR2(1:len_trim(TSTR2))
                      end if
                   end do
100                close(hFile1)
                end do  !--- end loop loop itest

                rewind(hFileH)
                rewind(hFile2)

                !---
                call STRCATI(GFILE, m_InFname, "P", 0, 4)
                GFILE = GFILE(1:len_trim(GFILE))//"_merged"
                if(EX) &
                   call STRCATI(GFILE, GFILE, ".", ICFG, 4)

                call AvailableIOUnit(hFile1)
                open(hFile1, file= GFILE, status='unknown')
                write(*,fmt="(A)") "Combined boxes output to "//GFILE(1:len_trim(GFILE))
                 do I=1, LINEH
                    read(hFileH, fmt="(A)" )TSTR1
                    if(I .eq. LINE) then
                       write(hFile1,fmt="(A, I)" )"&NATOM  ", NA2
                     else if(I .eq. LINENG) then
                        write(hFile1,* ) "&NGROUP   number of group of atoms:", NGROUP
                     else if(I .eq. LINENA) then
                        write(hFile1,* ) "    &NA   number of atoms in groups:", NA(1:NGROUP)
                      else  
                       write(hFile1,fmt="(A)" )TSTR1(1:len_trim(TSTR1))
                    end if
                 end do
                 do I=1, LINEA
                    read(hFile2, fmt="(A)")TSTR1
                    if(len_trim(TSTR1) .gt. 0) &
                       write(hFile1,fmt="(A)" )TSTR1(1:len_trim(TSTR1))
                 end do
                close(hFileH)
                close(hFile2)
                if(.not. EX) exit
             end do

             return
   end subroutine MergeCfg_ICfgSerial
  !**********************************************************************************

  !**********************************************************************************
   subroutine MergeCfg_ITestSerial()
  !***  DESCRIPTION: to merge a set of files of different ICFG but the same ITEST
  !
   implicit none
   !--- dummy variables
   !--- local variables for IO
         integer::ITEST, ICFG, hFile1, hFile2, hFileH, LINE, LINEH, LINEA, NA1, NA2, FLAG, N, I, NGROUP, NA(mp_MXGROUP), LINENG, LINENA
         character*256::GFILE
         character*1024::TSTR1, TSTR2
         character*64::KEYWORD, STRNUMB(10)
         logical::EX
   !-------------

             do ITEST = m_CtrlParam%JOBID0, m_CtrlParam%JOBID1, m_CtrlParam%JOBIDSTEP
                call AvailableIOUnit(hFile2)
                open(hFile2, status='SCRATCH')
                call AvailableIOUnit(hFileH)
                open(hFileH, status='SCRATCH')

                !--- load the data
                NA2 =  0
                FLAG = 0
                LINE = 0
                LINEH = 0
                LINEA = 0
                NGROUP = 0
                NA     = 0
                LINENG = 0
                LINENA = 0
                do ICFG = m_CtrlParam%STARTCFG,  m_CtrlParam%ENDCFG, m_CtrlParam%CFGSTEP
                   GFILE = m_InFname(1:len_trim(m_InFname))
                   call STRCATI(GFILE, GFILE, "P", 0, 4)
                   call STRCATI(GFILE, GFILE, "_", ITEST, 4)
                   call STRCATI(GFILE, GFILE, ".", ICFG, 4)
                   inquire(FILE=GFILE, EXIST=EX)
                   if(.not.EX) then
                      call MergeCfg_ICfgSerial()
                      exit
                   end if

                   write(*,*) "Load configure from ", GFILE(1:len_trim(GFILE))
                   call AvailableIOUnit(hFile1)
                   open(hFile1, file= GFILE, status='old')
                   do while(.true.)
                      read(hFile1, fmt="(A)", end=100 )TSTR1
                      TSTR2 = TSTR1
                      TSTR1 = adjustl(TSTR1)
                      if((TSTR1(1:1) .eq. '!') .or. (TSTR1(1:1) .eq. '&')  .or. len_trim(TSTR1) .le. 0) then
                         if(FLAG .eq. 0) then
                            LINEH = LINEH + 1
                            write(hFileH,fmt="(A)" )TSTR2(1:len_trim(TSTR2))
                         end if

                         if(TSTR1(1:1) .eq. '&') then
                             call GetKeyword("&", TSTR1, KEYWORD)
                             if (KEYWORD(1:len_trim(KEYWORD)) .eq. "&NATOM") then
                                 call Extract_Numb(TSTR1,1,N,STRNUMB)
                                 NA1 = ISTR(STRNUMB(1))
                                 NA2 = NA2 + NA1
                                 if(FLAG .eq. 0) LINE = LINEH
                              else if((KEYWORD(1:len_trim(KEYWORD)) .eq. "&NGROUP")) then   
                                 call Extract_Numb(TSTR1,1,N,STRNUMB)
                                 NGROUP = max(NGROUP, ISTR(STRNUMB(1)) )
                                 if(FLAG .eq. 0) LINENG = LINEH
                              else if((KEYWORD(1:len_trim(KEYWORD)) .eq. "&NA")) then   
                                 call Extract_Numb(TSTR1,mp_MXGROUP,N,STRNUMB)
                                 do I=1, N
                                    NA(I) = NA(I) + ISTR(STRNUMB(I))
                                 end do  
                                 if(FLAG .eq. 0) LINENA = LINEH 
                             end if
                         end if
                      else
                         FLAG = 1
                         LINEA = LINEA  + 1
                         write(hFile2,fmt="(A)" )TSTR2(1:len_trim(TSTR2))
                      end if
                   end do
100                close(hFile1)
                end do !--- end loop for ICFG
                rewind(hFileH)
                rewind(hFile2)
                if(.not.EX) exit

                !---
                call STRCATI(GFILE, m_InFname, "P", 0, 4)
                call STRCATI(GFILE, GFILE, "_", ITEST, 4)
                call AvailableIOUnit(hFile1)
                open(hFile1, file= GFILE, status='unknown')
                write(*,fmt="(A)") "Combined boxes output to "//GFILE(1:len_trim(GFILE))
                 do I=1, LINEH
                    read(hFileH, fmt="(A)" )TSTR1
                    if(I .eq. LINE) then
                       write(hFile1,fmt="(A, I)" )"&NATOM  ", NA2
                    else if(I .eq. LINENG) then
                       write(hFile1,* ) "&NGROUP   number of group of atoms:", NGROUP
                    else if(I .eq. LINENA) then
                       write(hFile1,* ) "    &NA   number of atoms in groups:", NA(1:NGROUP)
                    else
                       write(hFile1,fmt="(A)" )TSTR1(1:len_trim(TSTR1))
                    end if
                 end do
                 do I=1, LINEA
                    read(hFile2, fmt="(A)")TSTR1
                    write(hFile1,fmt="(A)" )TSTR1(1:len_trim(TSTR1))
                 end do
                close(hFileH)
                close(hFile2)
             end do

             return
   end subroutine MergeCfg_ITestSerial
  !**********************************************************************************

  !**********************************************************************************
   subroutine MergeCfg()
   implicit none
             if(m_CtrlParam%TIMELOOPOUT) then
                call MergeCfg_ITestSerial()
             else
                call MergeCfg_ICfgSerial()
             end if
   end subroutine MergeCfg
 !**********************************************************************************
 end module XYZData_Merge
 !**********************************************************************************


 !**********************************************************************************
 Program XYZData_Merge_Main
 use XYZData_Merge
 implicit none

       call Initialize()
       call MergeCfg()

       stop
 End program XYZData_Merge_Main
