 !**** DESCRIPTION: _______________________________________________________________________________________
 !                  This program is used to extract the displacement distribution and waiting time distribution
 !                  of SIA, from the file generated by SIADiffusion_GPU.F90 
 !
 !**** USAGE:       _______________________________________________________________________________________
 !                  JumpRate0.F90.exe -I "filename" -t(est) t1, t2, ts -c(fg) c1, c2, cs 
 !                  ______________________________________________________________________________________
 !**** HISTORY:
 !                  1st version   2019-04 (Hou Qing Sichuan university)
 !
 !
 
 !**********************************************************************************
 Program JumpRate0_Main
 use MD_SimBoxArray_ToolShell_14_CPU
 implicit none
    type(SimMDCtrl)    ::CtrlParam
    character*256      ::InFname  = "", OutFname=""
    character*256      ::GFile0="", GFile1   = "" 
    character*1024     ::tstr=""
    character(len=32),dimension(100)::nstr

    integer            ::hFile, hFile1, hFile2, hFile3, IB, NBOX=1000, NDEF, I, J, N, MIJMP, MXJMP, NJMP, NBIN, NREC, IBIN, ITIME0, ITIME1, &
                         IT, ITMI, ITMX, ITDIF, NIT, NJ1, NJ2, NJ3, IDIR, NDIR1(0:200),NDIR2(0:200),NDIR3(0:200)
    real(KINDDF)       ::MIWT, MXWT, PRET, CURT, WT, DWT , DX, DY, DZ, WTCUT, MSD1, MSD2, MSD3, DMSD1,DMSD2,DMSD3,TDIF, DDIR, DIR0, DIR1,CDIR(0:200)
    integer,      allocatable::NJUMP(:)
    real(KINDDF), allocatable::DT(:), HIS(:), DIS1(:,:,:), DIS2(:,:,:), DIS3(:,:,:), pDIS(:,:)
    real(KINDDF)       ::TIME0, VEC(3), DIS0(3), EKIN, EPOT, MSD0

      !*************************************
      ! The following varaibles are subjected to change
       NBOX=1000                   ! the number of box
       ITDIF = 100                 ! the timesteps of recording
       TDIF  = 0.01                ! the time interval of recording (in ps)
       WTCUT = 0.07D0               

      !*************************************
        call ExtractCmdlineFileNames_Globle_Variables()
        call CommandlineBoxsel(CtrlParam)
        InFname = gm_cfgFileName(1)
        call GetPath(InFname, OutFname)
        print *, OutFname

        call AvailableIOUnit(hFile)
        open(UNIT=hFile, FILE=InFname)
        allocate(NJUMP(NBOX))
        NJUMP = 0
        MIWT  = 1.D64
        MXWT  = 0
        ITMI  = 9999999
        ITMX  = 0
        NREC  = 0
      
        do I=1, size(nstr)
           nstr(I)  =""
        end do   
        ITIME0 = -1
        do while(.true.)
           read(hFile, *,END=100) tstr, IB
           if(tstr .ne. "&BOXID") then
              goto 100
           end if   
           NJUMP(IB) = NJUMP(IB) + 1
           if(ITIME0 .le. 0) then
             read(hFile, *) tstr, ITIME0
             if(ITIME0 .lt. ITMI) ITMI = ITIME0
             if(ITIME0 .gt. ITMX) ITMX = ITIME0
             NREC = NREC + 1
             print *, "IB= ",NREC, IB
            else
             read(hFile, *) tstr, ITIME1
             if(ITIME1.ne.ITIME0) then
                backspace(hFile)
                backspace(hFile)
                NJUMP(IB) = NJUMP(IB) - 1
                ITIME0 = -1
                cycle
             end if   
           end if            
           read(hFile, *) tstr, NDEF
           do I=1, NDEF
              read(hFile, fmt="(A)") tstr
              call Extract_Numb(tstr,size(nstr),N,nstr) 
              PRET = drstr(nstr(2))
              CURT = drstr(nstr(4))
              if(NJUMP(IB).ge.1) then
                 WT = CURT-PRET
                 if(WT.gt. MXWT)MXWT = WT
                 if(WT.lt. MIWT)MIWT = WT
              end if 
           end do
        end do      

100     rewind(hFile)
        call AvailableIOUnit(hFile1)
        open(UNIT=hFile1, FILE=OutFname(1:len_trim(OutFname)-1)//".dis")
        call AvailableIOUnit(hFile2)
        open(UNIT=hFile2, FILE=OutFname(1:len_trim(OutFname)-1)//".hist")
        call AvailableIOUnit(hFile3)
        open(UNIT=hFile3, FILE=OutFname(1:len_trim(OutFname)-1)//".sum")

        MIJMP = minval(NJUMP)
        MXJMP = maxval(NJUMP)
        NJMP  = MXJMP - MIJMP + 1
        NIT   = (ITMX - ITMI)/ITDIF + 1
        print *, "MJMP", MIJMP, MXJMP, NJMP
        print *, "MWT",  MIWT, MXWT
        print *, "NIT",  NIT
        
        NBIN = MXWT/MIWT + 1
        allocate(DT(NBIN), HIS(NBIN)) 
        do I=1, NBIN
           DT(I) = dble(I)*MIWT
        end do    
        HIS = 0.D0

        allocate(DIS1(NIT,NBOX,3), DIS2(NIT,NBOX,3), DIS3(NIT,NBOX,3), pDIS(NBOX,3))
        DIS1  = 0.D0
        DIS2  = 0.D0
        DIS3  = 0.D0
        pDIS  = 1.D10
        NDIR1 = 0
        NDIR2 = 0
        NDIR3 = 0
        CDIR = 1.D10

        ITIME0 = -1
        NJUMP  = 0
        NREC   = 0
        NJ1    = 0
        NJ2    = 0
        NJ3    = 0
        do while(.true.)
          read(hFile, *, END=200) tstr, IB
          NJUMP(IB) = NJUMP(IB) + 1
          if(ITIME0 .le. 0) then
             read(hFile, *) tstr, ITIME0
             NREC = NREC + 1
             print *, "RECORD J= ",NREC
          else
            read(hFile, *) tstr, ITIME1
            if(ITIME1.ne.ITIME0) then
               backspace(hFile)
               backspace(hFile)
               NJUMP(IB) = NJUMP(IB) - 1
               ITIME0 = -1
               cycle
            end if   
          end if     
          read(hFile, *) tstr, NDEF
          do I=1, NDEF
             read(hFile, fmt="(A)") tstr
             call Extract_Numb(tstr,size(nstr),N,nstr) 
             PRET = drstr(nstr(2))
             CURT = drstr(nstr(4))
             if(NJUMP(IB).ge.1) then
                WT = CURT-PRET
                IBIN = int((WT/MIWT)*0.99999D0) + 1
                HIS(IBIN) = HIS(IBIN) + 1
 
                DX = drstr(nstr(12))
                DY = drstr(nstr(13))
                DZ = drstr(nstr(14))

                IT = (ITIME0 - ITMI)/ITDIF + 1
                if(WT.le.WTCUT) then
                  DIS1(IT:NIT,IB,1) = DIS1(IT:NIT,IB,1) + DX
                  DIS1(IT:NIT,IB,2) = DIS1(IT:NIT,IB,2) + DY
                  DIS1(IT:NIT,IB,3) = DIS1(IT:NIT,IB,3) + DZ
                  NJ1               = NJ1 + 1
                else
                  DIS2(IT:NIT,IB,1) = DIS2(IT:NIT,IB,1) + DX
                  DIS2(IT:NIT,IB,2) = DIS2(IT:NIT,IB,2) + DY
                  DIS2(IT:NIT,IB,3) = DIS2(IT:NIT,IB,3) + DZ
                  NJ2               = NJ2 + 1
                end if
                DIS3(IT:NIT,IB,1) = DIS3(IT:NIT,IB,1) + DX
                DIS3(IT:NIT,IB,2) = DIS3(IT:NIT,IB,2) + DY
                DIS3(IT:NIT,IB,3) = DIS3(IT:NIT,IB,3) + DZ
                NJ3               = NJ3 + 1
                
                if(dabs(pDIS(IB,1)) .lt. 10) then
                  DIR0 = sum(pDIS(IB,1:3)*pDIS(IB,1:3))
                  DIR0 = dsqrt(DIR0)
                  DIR1 = DX*DX + DY*DY + DZ*DZ
                  DIR1 = dsqrt(DIR1)
                  DDIR = (pDIS(IB,1)*DX + pDIS(IB,2)*DY + pDIS(IB,3)*DZ)/(DIR0*DIR1)
                  IDIR = nint((DDIR + 1.D0)*100)
                  NDIR3(IDIR) = NDIR3(IDIR)+1
                  CDIR(IDIR)  = DDIR
                  if(WT.le.WTCUT) then
                     NDIR1(IDIR) = NDIR1(IDIR)+1
                  else   
                     NDIR2(IDIR) = NDIR2(IDIR)+1
                  end if   
                end if  
                pDIS(IB,1) = DX
                pDIS(IB,2) = DY
                pDIS(IB,3) = DZ
             end if 
          end do
        end do      
  200   close(hFile)  

        do I=1, NIT 
           MSD1 = 0.D0
           MSD2 = 0.D0
           MSD3 = 0.D0
           do J=1, NBOX
              MSD1 = MSD1 + DIS1(I,J,1)*DIS1(I,J,1) + DIS1(I,J,2)*DIS1(I,J,2) + DIS1(I,J,3)*DIS1(I,J,3)
              MSD2 = MSD2 + DIS2(I,J,1)*DIS2(I,J,1) + DIS2(I,J,2)*DIS2(I,J,2) + DIS2(I,J,3)*DIS2(I,J,3)
              MSD3 = MSD3 + DIS3(I,J,1)*DIS3(I,J,1) + DIS3(I,J,2)*DIS3(I,J,2) + DIS3(I,J,3)*DIS3(I,J,3)
           end do  
           MSD1 = MSD1/dble(NBOX)  
           MSD2 = MSD2/dble(NBOX)
           MSD3 = MSD3/dble(NBOX)
           DMSD1 = 0.D0
           DMSD2 = 0.D0
           DMSD3 = 0.D0
           do J=1, NBOX
            DMSD1 = DMSD1 + dabs(DIS1(I,J,1)*DIS1(I,J,1) + DIS1(I,J,2)*DIS1(I,J,2) + DIS1(I,J,3)*DIS1(I,J,3) - MSD1)
            DMSD2 = DMSD2 + dabs(DIS2(I,J,1)*DIS2(I,J,1) + DIS2(I,J,2)*DIS2(I,J,2) + DIS2(I,J,3)*DIS2(I,J,3) - MSD2)
            DMSD3 = DMSD3 + dabs(DIS3(I,J,1)*DIS3(I,J,1) + DIS3(I,J,2)*DIS3(I,J,2) + DIS3(I,J,3)*DIS3(I,J,3) - MSD3)
           end do  
          DMSD1 = (DMSD1/dble(NBOX))  
          DMSD2 = (DMSD2/dble(NBOX))
          DMSD3 = (DMSD3/dble(NBOX))
          write(hFile1,fmt="(10(1x,1PE13.7))") dble(I)*TDIF, MSD1, MSD2, MSD3, DMSD1, DMSD2, DMSD3
        end do

        do I=1, NBIN
           write(hFile2, fmt="(1PE14.7,1x,1PE14.7)") DT(I), HIS(I)
        end do   

        write(hFile3, fmt="(10(A,I8,1x))") "NJ1 ",NJ1, "NJ2 ",NJ2, "NJ3 ",NJ3
        do I=0, size(NDIR1)
           write(hFile3, fmt="(1x,1PE14.7,1x,10(I8,1x))") CDIR(I), NDIR1(I), NDIR2(I), NDIR3(I)
        end do 
        deallocate(NJUMP, DIS1, DIS2, DIS3)     
        deallocate(DT, HIS) 
        close(hFile1)
        close(hFile2)
        close(hFile3)
       stop
 End program JumpRate0_Main

