//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by wexpress.rc
//
#define IDS_ERROR                       1
#define IDS_WARNING                     2
#define IDS_PCLICKMSG                   3
#define IDS_TCLICKMSG                   4
#define IDS_BCLICKMSG                   5
#define IDS_Bempty                      6
#define IDS_StartCLICKMSG               7
#define IDS_PCLICKMSGOK                 8
#define IDS_TCLICKMSGOK                 9
#define IDS_NextCLICKMSG                10
#define IDS_ViewCLICKMSG                11
#define IDS_SUMMARY                     12
#define IDS_PARTCLE                     13
#define IDS_Target                      14
#define IDS_INPROCESS                   15
#define IDS_Init                        16
#define IDS_InitJob                     17
#define IDS_InitCSDA                    18
#define IDS_InitSCT                     19
#define IDR_MENU1                       101
#define ID_MENU_NEWJOB                  101
#define ID_MENU_NEWPRJ                  103
#define ID_MENU_SAVEJOBAS               104
#define ID_MENU_OPENPRJ                 104
#define ID_MENU_EXIT                    105
#define ID_MENU_OPENJOB                 106
#define ID_MENU_SAVEJOB                 108
#define IDC_PARTICLE                    1000
#define IDC_PMASS                       1001
#define IDC_PSYMBOL                     1002
#define IDC_PCHARGE                     1003
#define IDC_EDIT1                       1004
#define IDC_EDIT2                       1005
#define IDC_EDIT3                       1006
#define IDC_INCIDCONDITION              1009
#define IDC_CUSTOM1                     1010
#define IDC_LIST1                       1154
#define ID_MENU_DATAVIEW                20201
#define ID_MENU_FIGUREVIEW              20202
#define ID_MENUITEM40001                40001
#define ID_MENU_PAUSE                   40002
#define ID_MENU_REFLECT                 40003
#define ID_MENU_RANGE                   40004
#define ID_MENU_SELJOB                  40005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
